In [27]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [28]:
import pandas as pd

In [29]:
df = pd.DataFrame(people)

In [30]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [31]:
#Create column
df['full_name'] = df['first'] + ' ' + df['last']
df['fullname'] = df['first'] + ' ' + df['last']
df

   first     last                    email      full_name       fullname
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe       John Doe

In [32]:
#Remove column
df = df.drop(columns = ['full_name'])
df

   first     last                    email       fullname
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe

In [35]:
#Expand is set to column
df['fullname'].str.split(' ', expand = True)

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [38]:
#Separate create new column
df[['first', 'last']] = df['fullname'].str.split(' ', expand = True)
df

   first     last                    email       fullname
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe

In [42]:
#Add data a row
df._append({'first':'Zoom'}, ignore_index=True)

   first     last                    email       fullname
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe
3   Zoom      NaN                      NaN            NaN

In [44]:
people = {
    'first': ['Tony', 'Steve'],
    'last': ['Stark', 'Rogers'],
    'email': ['IronMan@avenge.com', 'Cap@avenge.com']
}
df2 = pd.DataFrame(people)

df2

   first    last               email
0   Tony   Stark  IronMan@avenge.com
1  Steve  Rogers      Cap@avenge.com

In [50]:
#Append data
df = df._append(df2, ignore_index=True, sort=False)

In [55]:
#Drop row specific by index
df = df.drop(index=4, axis=1)
df

   first     last                    email       fullname
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe
3   Tony    Stark       IronMan@avenge.com            NaN

In [58]:
filt = df[df['last'] == 'Doe'].index
df = df.drop(index = df[filt])
df

   first     last                    email       fullname
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
3   Tony    Stark       IronMan@avenge.com            NaN

In [34]:
# df = pd.read_csv('survey_results_public.csv')
# schema_df = pd.read_csv('survey_results_schema.csv')
#
# pd.set_option('display.max_columns', 85)
# pd.set_option('display.max_rows', 85)
#
# df