In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [5]:
df['email']

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: object

In [6]:
df.set_index('email', inplace=True)

In [7]:
df

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@email.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [8]:
df.index

Index(['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com'], dtype='object', name='email')

In [9]:
df.loc['CoreyMSchafer@gmail.com', 'last']

'Schafer'

In [10]:
df.iloc[0]

first      Corey
last     Schafer
Name: CoreyMSchafer@gmail.com, dtype: object

In [11]:
df.reset_index(inplace=True)
df

                     email  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer
1        JaneDoe@email.com   Jane      Doe
2        JohnDoe@email.com   John      Doe

In [14]:
schema_df = pd.read_csv("survey_results_schema.csv", index_col='qid')

In [15]:
schema_df

,qname,question,type,sub,sq_id
qid,,,,,
QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...
QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [18]:
schema_df.sort_index(ascending=True)

,qname,question,type,sub,sq_id
qid,,,,,
QID10,LearnCodeChoose,Did you begin learning to code or learn a new ...,MC,NaN,NaN
QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
QID102,AIAgentOrchWrite,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
...,...,...,...,...,...
QID91,AIAgentObserveSecure,You indicated you use or develop AI agents as ...,MC,NaN,NaN
QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN
QID97,SOFriction,"When you visit Stack Overflow, how often is it...",MC,NaN,NaN
QID99,AIFrustration,"When using AI tools, which of the following pr...",MC,NaN,NaN